default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2509
  host: localhost
  port: 5432

development:
  <<: *default
  database: site_adv_backend_development

test:
  <<: *default
  database: site_adv_backend_test

production:
  <<: *default
  database: site_adv_backend_production
  username: site_adv_backend
  password: <%= ENV["SITE_ADV_BACKEND_DATABASE_PASSWORD"] %>